version: 0.2

phases:
  pre_build:
    commands:
      - n 14.18.3
      - yarn install
  build:
    commands:
      - node_modules/.bin/quasar build
artifacts:
  files:
    - '**/*'
  base-directory: dist/spa

