version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - node_modules/.bin/quasar build
  post_build:
    commands:
      - aws s3 sync ./dist/spa s3://$BUCKET_NAME --acl 'public-read' --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"


