version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - node_modules/.bin/quasar build
  post_build:
    commands:
      - aws s3 sync ./dist/spa s3://spaceriders-api --acl 'public-read' --delete

